controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
 
check_bx24:
    path: /checkBx24
    controller: App\Controller\RunAppController::checkBx24 
